In [193]:
!pip3 install pandas numpy

Requirement already satisfied: pandas in .\.venv\Lib\site-packages (3.0.2)
Requirement already satisfied: numpy in .\.venv\Lib\site-packages (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in .\.venv\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in .\.venv\Lib\site-packages (from pandas) (2026.1)
Requirement already satisfied: six>=1.5 in .\.venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [194]:
# Task 1 — Explore and Identify Issues Load the dataset and use df.info(), df.describe(), and df.shape to report at least three data quality problems you observe (e.g., wrong dtypes, nulls, impossible values).

# Task 2 — Clean the Data Fix the issues identified: drop null target rows, impute missing input features, strip and lowercase the brand column, extract numeric values from the mileage column, and remove duplicates.

# Task 3 — Compute Baseline MAE Build a baseline model that predicts the mean selling_price for every record. Calculate and print the MAE of this baseline on the full cleaned dataset.

# Task -1  Explore and Identify Issues

In [ ]:
# Load the dataset and use df.info(), df.describe(), and df.shape to report at least three 
# data quality problems you observe (e.g., wrong dtypes, nulls, impossible values).

import pandas as pd

# file_id = "1HBukhaLOj9ZHpsFadIDxuINjk-G1jiB_"
# url = f"https://drive.google.com/uc?export=download&id={file_id}"

# df = pd.read_csv(url)


df = pd.read_csv("used_cars_messy.csv")

df.info()

df.describe()

df.isnull().sum() * 100 / df.shape[0]

# df.duplicated().sum()

<class 'pandas.DataFrame'>
RangeIndex: 15661 entries, 0 to 15660
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         15661 non-null  int64
 1   car_name           15661 non-null  str
 2   brand              15661 non-null  str
 3   model              15661 non-null  str
 4   vehicle_age        15661 non-null  int64
 5   km_driven          15661 non-null  str
 6   seller_type        15661 non-null  str
 7   fuel_type          15661 non-null  str
 8   transmission_type  15661 non-null  str
 9   mileage            14376 non-null  str
 10  engine             13792 non-null  float64
 11  max_power          14862 non-null  float64
 12  seats              15218 non-null  float64
 13  selling_price      15503 non-null  float64
dtypes: float64(4), int64(2), str(8)
memory usage: 1.7 MB

Unnamed: 0            0.000000
car_name              0.000000
brand                 0.000000
model                 0.000000
vehicle_age           0.000000
km_driven             0.000000
seller_type           0.000000
fuel_type             0.000000
transmission_type     0.000000
mileage               8.205095
engine               11.934104
max_power             5.101845
seats                 2.828683
selling_price         1.008876
dtype: float64

In [224]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)
pd.set_option('display.width', 120)

# Task -2 Data Cleaning (Clean the Data Fix the issues identified)

In [225]:
df['mileage'] = df['mileage'].str.strip().replace("kmpl","")

In [229]:
df['mileage'] = df['mileage'].str.replace({"kmpl":""})

In [236]:
df['mileage'] = pd.to_numeric(df["mileage"])

df['mileage'] = df['mileage'].fillna(df['mileage'].mean())

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 15661 entries, 0 to 15660
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         15661 non-null  int64
 1   car_name           15661 non-null  str
 2   brand              15661 non-null  str
 3   model              15661 non-null  str
 4   vehicle_age        15661 non-null  int64
 5   km_driven          15661 non-null  str
 6   seller_type        15661 non-null  str
 7   fuel_type          15661 non-null  str
 8   transmission_type  15661 non-null  str
 9   mileage            15661 non-null  float64
 10  engine             13792 non-null  float64
 11  max_power          14862 non-null  float64
 12  seats              15218 non-null  float64
 13  selling_price      15503 non-null  float64
dtypes: float64(5), int64(2), str(7)
memory usage: 1.7 MB

dropped the Unamed : 0 column (No usefull)

In [237]:
df = df.drop(columns=['Unnamed: 0'])

In [238]:
df

,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,Renault Duster,Renault,Duster,7,67647,Dealer,Diesel,Manual,19.870000,1461.0,83.80,5.0,575000.0
1,Maruti Wagon R,Maruti,Wagon R,3,52000,Dealer,CNG,Manual,33.540000,998.0,67.04,5.0,435000.0
2,Honda City,Honda,City,3,48959,Dealer,Petrol,Manual,19.703828,1497.0,117.60,5.0,875000.0
3,Mahindra Scorpio,Mahindra,Scorpio,6,82000,dealer,Diesel,Manual,15.400000,2179.0,NaN,8.0,925000.0
4,Mahindra XUV500,Mahindra,XUV500,4,34000,Dealer,Diesel,Automatic,16.000000,2179.0,140.00,7.0,1175000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
15656,Maruti Ertiga,Maruti,Ertiga,7,127731,Dealer,Diesel,Manual,20.770000,1248.0,88.80,7.0,665000.0
15657,Volkswagen Vento,Volkswagen,Vento,11,59000,Dealer,Petrol,Manual,16.090000,NaN,103.20,5.0,249000.0
15658,Maruti Wagon R,Maruti,Wagon R,7,20000,Individual,Petrol,Manual,20.510000,998.0,67.04,5.0,250000.0
15659,Hyundai i20,Hyundai,i20,2,15000,Dealer,Petrol,Manual,18.600000,1197.0,81.86,5.0,620000.0
15660,Maruti Ciaz,Maruti,Ciaz,2,30000,Individual,Petrol,Automatic,20.280000,1462.0,103.25,5.0,960000.0

Removing the White spaces in the car name column

In [239]:
df['car_name'] = df['car_name'].str.strip().str.title()

df['car_name']

0          Renault Duster
1          Maruti Wagon R
2              Honda City
3        Mahindra Scorpio
4         Mahindra Xuv500
               ...
15656       Maruti Ertiga
15657    Volkswagen Vento
15658      Maruti Wagon R
15659         Hyundai I20
15660         Maruti Ciaz
Name: car_name, Length: 15661, dtype: str

Removing the White spaces in the brand column

In [240]:

df['brand'] = df['brand'].str.strip().str.title()
df['brand'].unique()

<StringArray>
[      'Renault',        'Maruti',         'Honda',      'Mahindra',       'Hyundai',          'Ford',          'Jeep',
           'Bmw',        'Jaguar',         'Skoda',    'Volkswagen',          'Tata', 'Mercedes-Benz',        'Datsun',
          'Audi',         'Lexus',        'Toyota',        'Nissan',    'Land Rover',          'Mini',         'Volvo',
       'Porsche',           'Kia',            'Mg',         'Isuzu',  'Mercedes-Amg',       'Ferrari',       'Bentley',
      'Maserati',         'Force',   'Rolls-Royce']
Length: 31, dtype: str

Removing the White spaces in the Model column

In [241]:
df['model'] = df['model'].str.strip().str.title()
df['model'].unique()

<StringArray>
[      'Duster',      'Wagon R',         'City',      'Scorpio',       'Xuv500',          'I10',          'I20',
    'Freestyle',  'Swift Dzire',        'Swift',
 ...
          'S90',         'Aura',    'Gtc4Lusso',        'Macan',       'Altroz',  'Continental',       'Ghibli',
       'Gurkha', 'Quattroporte',        'Ghost']
Length: 120, dtype: str

Cleaning the string values and commas to numeric values in Km_driven column

In [242]:
print(df['km_driven'].sample(200).tolist())

['56494', '26000', '5000', '120000', '68000', '76000', '37895', '70000', '11510', '39983', '40000', '80000', '35000', '12800', '51000', '4500', '103000', '92380', '35760', '97000', '57812', '65000', '15000', '72000', '25000', '125000', '43500', '70000', '66000', '30000', '80000', '50080', '66000', '67000', '70000', '69000', '16320', '15735', '8700', '110000', '75000', '50000 km', '64705', '76400', '40000', '7883', '76500', '131473', '41615', '80220', '36889', '61198', '92000', '64000 kms', '28000', '49100', '58354', '62000', '49743', '30000', '110000', '64366', '16881', '21000', '32959', '49000', '65000', '3919', '15000', '64000', '20002', '180000', '10000', '61498', '83000', '37000', '10000', '94000', '89000', '98000', '66000', '45874', '60000', '52000', '10000', '50000', '29006', '117089', '50000', '68812', '40000', '110000', '35000', '11000', '36000', '200000', '29678', '11128', '42406', '35000', '75000', '61107', '44000', '50000', '95500', '40000', '40000', '73000', '80000', '30000', '50000', '47000', '46000', '46000', '77250', '81000', '55000', '25000', '62150', '20000', '78000', '50000', '73000', '40000', '60000', '69000', '13000', '35000', '98000', '65000', '31869', '110000', '62000 kms', '120000', '120000', '34000', '4500', '29000', '59000', '2000', '39513', '100000', '43405', '120000', '60000', '85600', '77795', '35000', '87000', '50000', '64300', '30008', '120000', '90000', '69141', '103500', '72000', '58980', '25000', '60000', '38100', '120000', '30000', '16000', '18000', '24000', '50000', '51000', '9800', '86000', '64000', '47592', '57000', '25000', '10000', '25000', '61000', '71245', '34000', '20001', '98398', '33066', '47000', '140000', '86000', '80000', '60000', '75001', '31000', '87000', '40000', '55598', '40000', '50000', '76000', '50000', '30000', '41586', '60000', '17550']

In [243]:
df[df['km_driven'].str.contains("km")]

,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
80,Mahindra Xuv500,Mahindra,Xuv500,6,42000 kms,Dealer,Diesel,Manual,15.100000,2179.0,140.00,7.0,950000.0
111,Volkswagen Polo,Volkswagen,Polo,4,32000 km,Dealer,Diesel,Manual,20.140000,1498.0,88.70,5.0,655000.0
244,Renault Duster,Renault,Duster,5,62000 kms,Individual,Diesel,Manual,19.870000,1461.0,83.80,5.0,700000.0
324,Hyundai I20,Hyundai,I20,9,40000 kms,Dealer,Diesel,Manual,21.900000,1396.0,NaN,5.0,435000.0
370,Ford Aspire,Ford,Aspire,5,43652 kms,Dealer,Petrol,Manual,18.160000,1196.0,86.80,5.0,430000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
15030,Maruti Swift Dzire,Maruti,Swift Dzire,7,70000 km,Individual,Diesel,Manual,23.400000,1248.0,74.00,5.0,575000.0
15170,Honda Amaze,Honda,Amaze,8,31497 kms,Dealer,Petrol,Manual,18.000000,1198.0,86.70,5.0,393000.0
15228,Bmw 3,Bmw,3,12,114000 km,Dealer,Petrol,Automatic,12.050000,1995.0,154.00,5.0,650000.0
15449,Hyundai I20,Hyundai,I20,3,15000 kms,Dealer,Petrol,Manual,18.600000,1197.0,81.83,5.0,660000.0
15602,Mahindra Xuv500,Mahindra,Xuv500,6,80000 kms,Individual,Diesel,Manual,19.703828,2179.0,140.00,7.0,925000.0

In [244]:
df['km_driven'] = df['km_driven'].str.strip().replace({"kms":"", "km":""})

In [245]:
df['km_driven'] = pd.to_numeric(df['km_driven'].str.replace(',', ''), errors='coerce')

In [246]:

df['km_driven'].dtype

dtype('float64')

In [256]:
df['km_driven'] = df['km_driven'].fillna(df['km_driven'].mean())

In [257]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 15661 entries, 0 to 15660
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   car_name           15661 non-null  str
 1   brand              15661 non-null  str
 2   model              15661 non-null  str
 3   vehicle_age        15661 non-null  int64
 4   km_driven          15661 non-null  float64
 5   seller_type        15661 non-null  str
 6   fuel_type          15661 non-null  str
 7   transmission_type  15661 non-null  str
 8   mileage            15661 non-null  float64
 9   engine             13792 non-null  float64
 10  max_power          14862 non-null  float64
 11  seats              15218 non-null  float64
 12  selling_price      15503 non-null  float64
dtypes: float64(6), int64(1), str(6)
memory usage: 1.6 MB

In [248]:
df.duplicated().sum()

np.int64(269)

Cleaning the seller_type column by changing the names

In [249]:
df['seller_type'].unique()

<StringArray>
['Dealer', 'dealer', 'Individual', 'individual', 'DEALER', 'Trustmark Dealer', 'Individul', 'Individuall', 'Delaer']
Length: 9, dtype: str

In [250]:
df['seller_type'] = df['seller_type'].str.replace({"Delaer":"dealer",
                                                    "Individul":"individual",
                                                    "Individuall":"individual"
                                                    }).str.title()

In [251]:
df['seller_type'].unique()
# cleaned

<StringArray>
['Dealer', 'Individual', 'Trustmark Dealer']
Length: 3, dtype: str

Changing the cases and removing whitespaces

In [252]:
df['fuel_type'] = df['fuel_type'].str.strip().str.title()

In [253]:
df['fuel_type'].unique()

<StringArray>
['Diesel', 'Cng', 'Petrol', 'Lpg', 'Electric']
Length: 5, dtype: str

In [254]:
df

,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,Renault Duster,Renault,Duster,7,67647.0,Dealer,Diesel,Manual,19.870000,1461.0,83.80,5.0,575000.0
1,Maruti Wagon R,Maruti,Wagon R,3,52000.0,Dealer,Cng,Manual,33.540000,998.0,67.04,5.0,435000.0
2,Honda City,Honda,City,3,48959.0,Dealer,Petrol,Manual,19.703828,1497.0,117.60,5.0,875000.0
3,Mahindra Scorpio,Mahindra,Scorpio,6,82000.0,Dealer,Diesel,Manual,15.400000,2179.0,NaN,8.0,925000.0
4,Mahindra Xuv500,Mahindra,Xuv500,4,34000.0,Dealer,Diesel,Automatic,16.000000,2179.0,140.00,7.0,1175000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
15656,Maruti Ertiga,Maruti,Ertiga,7,127731.0,Dealer,Diesel,Manual,20.770000,1248.0,88.80,7.0,665000.0
15657,Volkswagen Vento,Volkswagen,Vento,11,59000.0,Dealer,Petrol,Manual,16.090000,NaN,103.20,5.0,249000.0
15658,Maruti Wagon R,Maruti,Wagon R,7,20000.0,Individual,Petrol,Manual,20.510000,998.0,67.04,5.0,250000.0
15659,Hyundai I20,Hyundai,I20,2,15000.0,Dealer,Petrol,Manual,18.600000,1197.0,81.86,5.0,620000.0
15660,Maruti Ciaz,Maruti,Ciaz,2,30000.0,Individual,Petrol,Automatic,20.280000,1462.0,103.25,5.0,960000.0

In [255]:
df.isnull().sum()

car_name                0
brand                   0
model                   0
vehicle_age             0
km_driven             166
seller_type             0
fuel_type               0
transmission_type       0
mileage                 0
engine               1869
max_power             799
seats                 443
selling_price         158
dtype: int64

imputing the values in engine and max_power columns

In [258]:
for col in ['engine', 'max_power']:
    median_value = df[col].median()
    df[col] = df[col].fillna(median_value)

In [259]:
df['seats'] = df['seats'].fillna(df['seats'].mode()[0])

In [260]:
# df['selling_price'] = df['selling_price'].dropna()
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 15661 entries, 0 to 15660
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   car_name           15661 non-null  str
 1   brand              15661 non-null  str
 2   model              15661 non-null  str
 3   vehicle_age        15661 non-null  int64
 4   km_driven          15661 non-null  float64
 5   seller_type        15661 non-null  str
 6   fuel_type          15661 non-null  str
 7   transmission_type  15661 non-null  str
 8   mileage            15661 non-null  float64
 9   engine             15661 non-null  float64
 10  max_power          15661 non-null  float64
 11  seats              15661 non-null  float64
 12  selling_price      15503 non-null  float64
dtypes: float64(6), int64(1), str(6)
memory usage: 1.6 MB

dropping the null values in the target variable

In [261]:
df = df.dropna(subset=['selling_price'])

df.info()

<class 'pandas.DataFrame'>
Index: 15503 entries, 0 to 15660
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   car_name           15503 non-null  str
 1   brand              15503 non-null  str
 2   model              15503 non-null  str
 3   vehicle_age        15503 non-null  int64
 4   km_driven          15503 non-null  float64
 5   seller_type        15503 non-null  str
 6   fuel_type          15503 non-null  str
 7   transmission_type  15503 non-null  str
 8   mileage            15503 non-null  float64
 9   engine             15503 non-null  float64
 10  max_power          15503 non-null  float64
 11  seats              15503 non-null  float64
 12  selling_price      15503 non-null  float64
dtypes: float64(6), int64(1), str(6)
memory usage: 1.7 MB

In [265]:
df.duplicated().sum()
df = df.drop_duplicates()

df.info()

<class 'pandas.DataFrame'>
Index: 15205 entries, 0 to 15660
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   car_name           15205 non-null  str
 1   brand              15205 non-null  str
 2   model              15205 non-null  str
 3   vehicle_age        15205 non-null  int64
 4   km_driven          15205 non-null  float64
 5   seller_type        15205 non-null  str
 6   fuel_type          15205 non-null  str
 7   transmission_type  15205 non-null  str
 8   mileage            15205 non-null  float64
 9   engine             15205 non-null  float64
 10  max_power          15205 non-null  float64
 11  seats              15205 non-null  float64
 12  selling_price      15205 non-null  float64
dtypes: float64(6), int64(1), str(6)
memory usage: 1.6 MB

In [266]:
df.duplicated().sum()

np.int64(0)

# TASK - 3 Compute Baseline MAE

In [267]:

import numpy as np

y = df['selling_price']

# Baseline Prediction

mean_price = y.mean()
y_pred = np.full(len(df) , mean_price)

# MAE Calculation
mae = np.mean(np.abs(y - y_pred))

print(mae)

870858.5602497318